### ISSUE TITLE
Changes saved in workspace cause conflicts in repos with different users

### ISSUE THREAD

**Issue by JohnCampionJr** [ChrisBibby/vscode_hide-node-modules#338]
Hi, this is a very useful extension.  However, in my project with different developers, we have different preferences on whether or not we want to see node_modules.  So this causes differences in the workspace files.

I am submitting a PR to add an option to this extension to set the exclusion at the user level rather than workspace level.  

Thanks!

**Comment by ChrisBibby** [comment]
Cheers, will take a look 👍

**Comment by JohnCampionJr** [comment]
Yeah, I actually had code that would remove the exclusion from workspace but decided not to commit as I was thinking the extension shouldn't mess with the workspace files at all.  But I'd be happy with it however you want to implement it :)

**Comment by ChrisBibby** [comment]
I'm not too bothered about modifying the workspace as that is how the extension works anyway, I'll just update the readme to explain what happens when switching from workspace to user settings. 

Just pushed a new pre-release version to the marketplace so it should be available from VSCode - let me know how it goes. 

Cheers
